-- Add default templates for ticket management with Kruit & Kramer branding
-- Run this in phpMyAdmin or MySQL client

-- Resolution Templates (voor ticket afsluiten)
INSERT INTO `ticket_templates` (`name`, `description`, `content`, `template_type`, `created_by`, `is_active`) VALUES
('Ticket Succesvol Afgesloten', 'Standaard template voor succesvolle afsluiting', '<p><strong>Beste [Naam],</strong></p><p>Uw ticket is succesvol afgehandeld en opgelost.</p><p><strong>Uitgevoerde acties:</strong></p><ul><li>[Beschrijf hier de uitgevoerde acties]</li></ul><p><strong>Resultaat:</strong><br>Het probleem is opgelost en u kunt weer verder werken.</p><p>Mocht u nog vragen hebben of het probleem opnieuw optreden, aarzel dan niet om contact met ons op te nemen.</p><hr><p>Met vriendelijke groet,</p><p><strong>Damian Kessler</strong><br>ICT Medewerker</p><p><img src="http://localhost/ticketportaal/assets/images/logo/Kruit/logo.svg" alt="Kruit & Kramer" style="max-width: 150px; margin-top: 10px;"><br><strong>Kruit & Kramer</strong><br>ICT Support Team<br>Email: support@kruitkramer.nl<br>Tel: 777 / ICT afdeling intern</p>', 'resolution', 1, 1),

('Probleem Opgelost - Configuratie Aangepast', 'Voor configuratie wijzigingen', '<p><strong>Beste [Naam],</strong></p><p>Het gemelde probleem is opgelost door een configuratie aanpassing.</p><p><strong>Wat is er aangepast:</strong></p><ul><li>[Beschrijf de configuratie wijziging]</li><li>[Eventuele impact of wijzigingen voor gebruiker]</li></ul><p><strong>Actie vereist:</strong><br>[Indien van toepassing: beschrijf wat gebruiker moet doen]</p><p>De wijzigingen zijn direct actief. Test de functionaliteit en laat het ons weten als er nog problemen zijn.</p><hr><p>Met vriendelijke groet,</p><p><strong>Damian Kessler</strong><br>ICT Medewerker</p><p><img src="http://localhost/ticketportaal/assets/images/logo/Kruit/logo.svg" alt="Kruit & Kramer" style="max-width: 150px; margin-top: 10px;"><br><strong>Kruit & Kramer</strong><br>ICT Support Team<br>Email: support@kruitkramer.nl<br>Tel: 777 / ICT afdeling intern</p>', 'resolution', 1, 1),

('Probleem Opgelost - Software Update', 'Voor software updates/patches', '<p><strong>Beste [Naam],</strong></p><p>Het probleem is opgelost door een software update uit te voeren.</p><p><strong>Details:</strong></p><ul><li><strong>Software:</strong> [Naam software]</li><li><strong>Oude versie:</strong> [Versienummer]</li><li><strong>Nieuwe versie:</strong> [Versienummer]</li><li><strong>Wijzigingen:</strong> [Belangrijkste verbeteringen]</li></ul><p><strong>Let op:</strong><br>[Eventuele wijzigingen in gebruik of nieuwe functies]</p><p>De update is succesvol geïnstalleerd en getest. U kunt de software weer normaal gebruiken.</p><hr><p>Met vriendelijke groet,</p><p><strong>Damian Kessler</strong><br>ICT Medewerker</p><p><img src="http://localhost/ticketportaal/assets/images/logo/Kruit/logo.svg" alt="Kruit & Kramer" style="max-width: 150px; margin-top: 10px;"><br><strong>Kruit & Kramer</strong><br>ICT Support Team<br>Email: support@kruitkramer.nl<br>Tel: 777 / ICT afdeling intern</p>', 'resolution', 1, 1),

('Ticket Afgesloten - Geen Actie Nodig', 'Voor tickets die geen actie vereisen', '<p><strong>Beste [Naam],</strong></p><p>Na analyse van uw melding blijkt dat er geen actie nodig is.</p><p><strong>Reden:</strong></p><ul><li>[Uitleg waarom geen actie nodig is]</li><li>[Eventuele achtergrond informatie]</li></ul><p>Mocht u toch verdere ondersteuning nodig hebben, kunt u een nieuw ticket aanmaken of reageren op dit ticket.</p><hr><p>Met vriendelijke groet,</p><p><strong>Damian Kessler</strong><br>ICT Medewerker</p><p><img src="http://localhost/ticketportaal/assets/images/logo/Kruit/logo.svg" alt="Kruit & Kramer" style="max-width: 150px; margin-top: 10px;"><br><strong>Kruit & Kramer</strong><br>ICT Support Team<br>Email: support@kruitkramer.nl<br>Tel: 777 / ICT afdeling intern</p>', 'resolution', 1, 1),

-- Comment Templates (voor communicatie tijdens behandeling)
('Meer Informatie Nodig', 'Vraag om aanvullende informatie', '<p><strong>Beste [Naam],</strong></p><p>Om uw ticket goed te kunnen behandelen, hebben wij aanvullende informatie nodig:</p><ul><li>[Vraag 1]</li><li>[Vraag 2]</li><li>[Vraag 3]</li></ul><p><strong>Graag ontvangen wij:</strong></p><ul><li>Screenshots van het probleem (indien van toepassing)</li><li>Exacte foutmeldingen</li><li>Tijdstip waarop het probleem optreedt</li></ul><p>Zodra wij deze informatie hebben ontvangen, kunnen wij verder met de behandeling van uw ticket.</p><hr><p>Met vriendelijke groet,</p><p><strong>Damian Kessler</strong><br>ICT Medewerker</p><p><img src="http://localhost/ticketportaal/assets/images/logo/Kruit/logo.svg" alt="Kruit & Kramer" style="max-width: 150px; margin-top: 10px;"><br><strong>Kruit & Kramer</strong><br>ICT Support Team</p>', 'comment', 1, 1),

('In Behandeling - Analyse Gestart', 'Bevestiging dat ticket in behandeling is', '<p><strong>Beste [Naam],</strong></p><p>Uw ticket is in behandeling genomen en wij zijn gestart met de analyse van het probleem.</p><p><strong>Huidige status:</strong></p><ul><li>Ticket toegewezen aan: [Naam agent]</li><li>Verwachte oplostijd: [Tijdsindicatie]</li><li>Prioriteit: [Prioriteit niveau]</li></ul><p>Wij houden u op de hoogte van de voortgang. Mocht u tussentijds vragen hebben, kunt u reageren op dit ticket.</p><hr><p>Met vriendelijke groet,</p><p><strong>Damian Kessler</strong><br>ICT Medewerker</p><p><img src="http://localhost/ticketportaal/assets/images/logo/Kruit/logo.svg" alt="Kruit & Kramer" style="max-width: 150px; margin-top: 10px;"><br><strong>Kruit & Kramer</strong><br>ICT Support Team</p>', 'comment', 1, 1),

('Wijziging Verwerkt', 'Bevestiging van doorgevoerde wijziging', '<p><strong>Beste [Naam],</strong></p><p>De door u gevraagde wijziging is succesvol verwerkt.</p><p><strong>Doorgevoerde wijzigingen:</strong></p><ul><li>[Wijziging 1]</li><li>[Wijziging 2]</li><li>[Wijziging 3]</li></ul><p><strong>Ingangsdatum:</strong> [Datum en tijd]</p><p>De wijzigingen zijn direct actief. Controleer of alles naar wens werkt en laat het ons weten als er aanpassingen nodig zijn.</p><hr><p>Met vriendelijke groet,</p><p><strong>Damian Kessler</strong><br>ICT Medewerker</p><p><img src="http://localhost/ticketportaal/assets/images/logo/Kruit/logo.svg" alt="Kruit & Kramer" style="max-width: 150px; margin-top: 10px;"><br><strong>Kruit & Kramer</strong><br>ICT Support Team</p>', 'comment', 1, 1),

('Account Gegevens Verstrekt', 'Voor het verstrekken van account informatie', '<p><strong>Beste [Naam],</strong></p><p>Uw account is aangemaakt en de gegevens zijn als volgt:</p><p><strong>Account informatie:</strong></p><ul><li><strong>Gebruikersnaam:</strong> [Gebruikersnaam]</li><li><strong>E-mailadres:</strong> [E-mailadres]</li><li><strong>Toegang tot:</strong> [Systemen/Applicaties]</li></ul><p><strong>Eerste keer inloggen:</strong></p><ol><li>U ontvangt een aparte e-mail met uw tijdelijke wachtwoord</li><li>Log in met uw gebruikersnaam en tijdelijke wachtwoord</li><li>U wordt gevraagd een nieuw wachtwoord in te stellen</li></ol><p><strong>Wachtwoord eisen:</strong></p><ul><li>Minimaal 8 tekens</li><li>Minimaal 1 hoofdletter</li><li>Minimaal 1 cijfer</li><li>Minimaal 1 speciaal teken</li></ul><p>Mocht u problemen ondervinden bij het inloggen, neem dan contact met ons op.</p><hr><p>Met vriendelijke groet,</p><p><strong>Damian Kessler</strong><br>ICT Medewerker</p><p><img src="http://localhost/ticketportaal/assets/images/logo/Kruit/logo.svg" alt="Kruit & Kramer" style="max-width: 150px; margin-top: 10px;"><br><strong>Kruit & Kramer</strong><br>ICT Support Team</p>', 'comment', 1, 1),

('Wachtend op Externe Partij', 'Voor tickets die wachten op derden', '<p><strong>Beste [Naam],</strong></p><p>Uw ticket is momenteel in behandeling, maar wij wachten op een reactie van een externe partij.</p><p><strong>Details:</strong></p><ul><li><strong>Externe partij:</strong> [Naam leverancier/partij]</li><li><strong>Verwachte reactietijd:</strong> [Tijdsindicatie]</li><li><strong>Referentienummer:</strong> [Ticket/case nummer bij externe partij]</li></ul><p>Zodra wij een reactie hebben ontvangen, gaan wij direct verder met de behandeling van uw ticket. Wij houden u op de hoogte.</p><hr><p>Met vriendelijke groet,</p><p><strong>Damian Kessler</strong><br>ICT Medewerker</p><p><img src="http://localhost/ticketportaal/assets/images/logo/Kruit/logo.svg" alt="Kruit & Kramer" style="max-width: 150px; margin-top: 10px;"><br><strong>Kruit & Kramer</strong><br>ICT Support Team</p>', 'comment', 1, 1),

('Tijdelijke Oplossing - Workaround', 'Voor tijdelijke oplossingen', '<p><strong>Beste [Naam],</strong></p><p>Wij hebben een tijdelijke oplossing (workaround) voor uw probleem.</p><p><strong>Tijdelijke oplossing:</strong></p><ol><li>[Stap 1]</li><li>[Stap 2]</li><li>[Stap 3]</li></ol><p><strong>Let op:</strong> Dit is een tijdelijke oplossing. Wij werken aan een definitieve oplossing.</p><p><strong>Status definitieve oplossing:</strong><br>[Beschrijf de voortgang van de definitieve oplossing]</p><p>U kunt met deze workaround verder werken. Wij houden u op de hoogte van de definitieve oplossing.</p><hr><p>Met vriendelijke groet,</p><p><strong>Damian Kessler</strong><br>ICT Medewerker</p><p><img src="http://localhost/ticketportaal/assets/images/logo/Kruit/logo.svg" alt="Kruit & Kramer" style="max-width: 150px; margin-top: 10px;"><br><strong>Kruit & Kramer</strong><br>ICT Support Team</p>', 'comment', 1, 1),

('Geplande Onderhoudsmelding', 'Voor geplande onderhoudswerkzaamheden', '<p><strong>Beste [Naam],</strong></p><p>In verband met uw ticket willen wij u informeren over geplande onderhoudswerkzaamheden.</p><p><strong>Onderhoudsdetails:</strong></p><ul><li><strong>Datum:</strong> [Datum]</li><li><strong>Tijd:</strong> [Starttijd] - [Eindtijd]</li><li><strong>Betrokken systemen:</strong> [Systemen/Applicaties]</li><li><strong>Verwachte impact:</strong> [Beschrijving impact]</li></ul><p><strong>Wat betekent dit voor u:</strong><br>[Uitleg over de gevolgen voor de gebruiker]</p><p>Na het onderhoud verwachten wij dat uw probleem is opgelost. Wij houden u op de hoogte.</p><hr><p>Met vriendelijke groet,</p><p><strong>Damian Kessler</strong><br>ICT Medewerker</p><p><img src="http://localhost/ticketportaal/assets/images/logo/Kruit/logo.svg" alt="Kruit & Kramer" style="max-width: 150px; margin-top: 10px;"><br><strong>Kruit & Kramer</strong><br>ICT Support Team</p>', 'comment', 1, 1),

-- Change Management Templates
('Change Afgekeurd', 'Template voor afwijzing van change request', '<p><strong>Change Request Afgekeurd</strong></p><p>Uw change request is beoordeeld en helaas afgekeurd.</p><p><strong>Reden van afwijzing:</strong></p><p>[Beschrijf hier de reden waarom de change is afgekeurd]</p><p><strong>Aanbevelingen:</strong></p><ul><li>[Aanbeveling 1]</li><li>[Aanbeveling 2]</li></ul><p><strong>Vervolgstappen:</strong></p><ul><li>U kunt de change aanpassen en opnieuw indienen</li><li>Neem contact op met de Change Manager voor meer informatie</li><li>Overweeg alternatieve oplossingen</li></ul><p>Voor vragen kunt u contact opnemen met het Change Management team.</p><hr><p>Met vriendelijke groet,</p><p><strong>Damian Kessler</strong><br>ICT Medewerker<br>Change Management Team</p><p><img src="http://localhost/ticketportaal/assets/images/logo/Kruit/logo.svg" alt="Kruit & Kramer" style="max-width: 150px; margin-top: 10px;"><br><strong>Kruit & Kramer</strong><br>Email: change@kruitkramer.nl<br>Tel: 777 / ICT afdeling intern</p>', 'comment', 1, 1),

('Change Goedgekeurd', 'Template voor goedkeuring van change request', '<p><strong>Change Request Goedgekeurd</strong></p><p>Uw change request is beoordeeld en goedgekeurd.</p><p><strong>Goedgekeurde change:</strong></p><ul><li><strong>Change ID:</strong> [Change nummer]</li><li><strong>Titel:</strong> [Change titel]</li><li><strong>Geplande uitvoering:</strong> [Datum en tijd]</li></ul><p><strong>Volgende stappen:</strong></p><ol><li>Change wordt ingepland in de change kalender</li><li>Betrokken partijen worden geïnformeerd</li><li>Implementatie wordt voorbereid</li><li>U ontvangt een bevestiging voor de uitvoering</li></ol><p><strong>Belangrijk:</strong></p><ul><li>Zorg dat alle voorbereidingen zijn getroffen</li><li>Communiceer eventuele wijzigingen tijdig</li><li>Houd rekening met de geplande downtime</li></ul><hr><p>Met vriendelijke groet,</p><p><strong>Damian Kessler</strong><br>ICT Medewerker<br>Change Management Team</p><p><img src="http://localhost/ticketportaal/assets/images/logo/Kruit/logo.svg" alt="Kruit & Kramer" style="max-width: 150px; margin-top: 10px;"><br><strong>Kruit & Kramer</strong><br>Email: change@kruitkramer.nl<br>Tel: 777 / ICT afdeling intern</p>', 'comment', 1, 1),

('Change In Uitvoering', 'Template voor change in uitvoering', '<p><strong>Change In Uitvoering</strong></p><p>De goedgekeurde change wordt momenteel uitgevoerd.</p><p><strong>Status:</strong></p><ul><li><strong>Start uitvoering:</strong> [Datum en tijd]</li><li><strong>Verwachte eindtijd:</strong> [Datum en tijd]</li><li><strong>Huidige fase:</strong> [Beschrijving huidige fase]</li></ul><p><strong>Voortgang:</strong></p><ol><li>[Stap 1] - ✓ Voltooid</li><li>[Stap 2] - ⏳ In uitvoering</li><li>[Stap 3] - ⏸ Nog te doen</li></ol><p>Wij houden u op de hoogte van de voortgang. Bij vragen of problemen kunt u contact opnemen met het implementatie team.</p><hr><p>Met vriendelijke groet,</p><p><strong>Damian Kessler</strong><br>ICT Medewerker<br>Change Management Team</p><p><img src="http://localhost/ticketportaal/assets/images/logo/Kruit/logo.svg" alt="Kruit & Kramer" style="max-width: 150px; margin-top: 10px;"><br><strong>Kruit & Kramer</strong><br>Email: change@kruitkramer.nl<br>Tel: 777 / ICT afdeling intern</p>', 'comment', 1, 1),

('Change Succesvol Afgerond', 'Template voor succesvolle change', '<p><strong>Change Succesvol Afgerond</strong></p><p>De change is succesvol uitgevoerd en afgerond.</p><p><strong>Resultaat:</strong></p><ul><li><strong>Uitgevoerd op:</strong> [Datum en tijd]</li><li><strong>Duur:</strong> [Tijdsduur]</li><li><strong>Status:</strong> Succesvol afgerond</li></ul><p><strong>Doorgevoerde wijzigingen:</strong></p><ul><li>[Wijziging 1]</li><li>[Wijziging 2]</li><li>[Wijziging 3]</li></ul><p><strong>Verificatie:</strong></p><ul><li>Alle testen zijn succesvol uitgevoerd</li><li>Systemen zijn operationeel</li><li>Geen onverwachte problemen geconstateerd</li></ul><p><strong>Actie vereist:</strong><br>[Indien van toepassing: beschrijf wat gebruikers moeten doen]</p><p>Mocht u problemen ondervinden na deze change, neem dan direct contact met ons op.</p><hr><p>Met vriendelijke groet,</p><p><strong>Damian Kessler</strong><br>ICT Medewerker<br>Change Management Team</p><p><img src="http://localhost/ticketportaal/assets/images/logo/Kruit/logo.svg" alt="Kruit & Kramer" style="max-width: 150px; margin-top: 10px;"><br><strong>Kruit & Kramer</strong><br>Email: change@kruitkramer.nl<br>Tel: 777 / ICT afdeling intern</p>', 'comment', 1, 1);

